
# SEO settings
title: "Expo"
title2: ":exlore" # default: ""
description: "Just another minimalist Jekyll theme for technical writing."
keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url: http://i6ruce.github.io/Expo # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/i6ruce/Expo
disqus_shortname: ""
twitter_username: "i6ruce1"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Expo Dev"
  job      : "Software Engineer"
  bio      : "Some very important words"
  thumb    : /images/author.jpg
  email    : expodev@gmail.com
  url      : http://i6ruce.github.io
  github   : http://github.com/i6ruce
  twitter  : http://twitter.com/i6ruce1
  facebook : https://www.facebook.com/
  linkedin : http://linkedin.com/in/

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@i6ruce1"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
